### ISSUE TITLE
DB creation 

### ISSUE THREAD

**Issue by 65monroe** [dvmonroe/hubspot#1]
There was no create db so i just went into postgres created a db and added a user... the password and user were commented out so un commented and add in the credentials should that be part of the .env file?

**Comment by dvmonroe** [comment]
@65monroe I think it may have errored b/c you needed to add a user and pword to access postrgres.  It should work if you added your credentials and you try a `rake db:drop` and then retry `rake db:create` again.  Let me know. If not I can add additional code to make sure you're in postgres before trying to create.
